### ISSUE TITLE
document IP adress usage

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/documentation#1]
Write a source article on how to doc IP Adresses

IP adresses are here:
https://docs.google.com/spreadsheets/d/1iwXilV1V84IQN7mKOIHq28-9P5bWabN019TJPaJ_3Es/edit#gid=1735312685&range=I4

**Comment by mschindl** [comment]
@DanielFroehlich the spreadsheet was updated. Is your issue still valid?

**Comment by rbo** [comment]
Documentation starting point for COE Network is: [02 COE Network Configuration](https://docs.google.com/document/d/1OJXD2ftYDsLkWkUlWP1nAu7u2PLVho8_4sdNvxbd7D0/edit#) and for detailed addresses [COE Muc Lab Documentation](https://docs.google.com/spreadsheets/d/1iwXilV1V84IQN7mKOIHq28-9P5bWabN019TJPaJ_3Es/edit#gid=1735312685&range=I4)

**Comment by rbo** [comment]
A Link to both documents in source should be enough.
