### ISSUE TITLE
"OpenShift V4 UPI installation instructions" - still necessary?

### ISSUE THREAD

**Issue by mschindl** [stormshift/documentation#2]
As I understood the generic installation is based on IPI now and following page can be deleted, right?
https://source.redhat.com/groups/public/solution-architects/stormshift/stormshift_wiki/openshift_v4_installation_instructions

> current installation method:
https://source.redhat.com/groups/public/solution-architects/stormshift/stormshift_wiki/install_openshift_v4_cluster_using_rhv_ipi

**Comment by DanielFroehlich** [comment]
you are right, but I would like to keep the old UPI instructions for historical reasons, maybe maybe maybe it would help to take a look at that again. Usually, documentation dies first. This time, it dies last ;-)
